"""
Write a Zemax ZMX file from optimizer JSON output.

Usage:
    python write_zmx.py optimized_20260414_111700.json
"""

import sys
import os
import json


def write_zmx(filepath, data):
    """Write a Zemax ZMX file from optimizer result data."""
    n = data['n_elements']
    efl = data['result']['efl']
    f_number = data['f_number']
    field_deg = data['field_angle_deg']
    stop_idx = data['stop_idx']
    enpd = efl / f_number

    lines = []
    lines.append("VERS 231205 106 20120530 20120530")
    lines.append("MODE SEQ")
    lines.append(f"NAME Optimized {n}-element f/{f_number}")
    lines.append("AUTH ")
    lines.append("IWDP 0")
    lines.append("NOTE 0 Generated by write_zmx.py")
    lines.append("PFIL 0 0 0")
    lines.append("LANG 0")
    lines.append("UNIT MM X W X CM MR CPMM")
    lines.append(f"ENPD {enpd:.10f}")
    lines.append("ENVD 20 1 0")
    lines.append("GFAC 0 0")
    lines.append("GCAT SCHOTT ")
    lines.append("RAIM 0 0 1 1 0 0 0 0 0 1")
    lines.append("PUSH 0 0 0 0 0 0")
    lines.append("SDMA 0 1 0")
    lines.append("OMMA 1 1")
    lines.append("FTYP 0 0 3 3 0 0 0 3")
    lines.append("ROPD 2")
    lines.append("HYPR 0")
    lines.append("PICB 1")
    lines.append("XFLN 0 0 0")
    lines.append(f"YFLN 0 {field_deg/2:.1f} {field_deg:.1f}")
    lines.append("FWGN 1 1 1")
    lines.append("VDXN 0 0 0")
    lines.append("VDYN 0 0 0")
    lines.append("VCXN 0 0 0")
    lines.append("VCYN 0 0 0")
    lines.append("VANN 0 0 0")
    lines.append("WAVM 1 0.48613269999999997 1")
    lines.append("WAVM 2 0.58756180000000002 1")
    lines.append("WAVM 3 0.65627250000000004 1")
    lines.append("PWAV 2")
    lines.append("POLS 1 0 1 0 0 1 0")
    lines.append("GLRS 1 0")
    lines.append("GSTD 0 100.000 100.000 100.000 100.000 100.000 100.000"
                 " 0 1 1 0 0 1 1 1 1 1 1")
    lines.append("NSCD 100 500 0 0.001 10 9.99999999999999995e-07"
                 " 0 0 0 0 0 0 1000000 0 2")
    lines.append("COFN QF \"COATING.DAT\" \"SCATTER_PROFILE.DAT\""
                 " \"ABG_DATA.DAT\" \"PROFILE.GRD\"")
    lines.append("COFN COATING.DAT SCATTER_PROFILE.DAT"
                 " ABG_DATA.DAT PROFILE.GRD")
    lines.append("LUID 15")
    lines.append("EERA 0 0 0 10")

    # Object surface
    lines.append("SURF 0")
    lines.append("    SSID 0")
    lines.append("    TYPE STANDARD")
    lines.append("    FIMP ")
    lines.append("    CURV 0.0 0 0 0 0 \"\"")
    lines.append("    HIDE 0 0 0 0 0 0 0 0 0 0 0 0")
    lines.append("    MIRR 2 0")
    lines.append("    SLAB 0")
    lines.append("    DISZ INFINITY")
    lines.append("    DIAM 0 0 0 0 1 \"\"")
    lines.append("    MEMA 0 0 0 0 1 \"\"")
    lines.append("    POPS 0 0 0 0 0 0 0 0 1 1 1 1 0 0 0 0")

    surf_num = 1
    for i, elem in enumerate(data['elements']):
        nd = elem['n_d']

        # Front surface
        is_stop = (surf_num == stop_idx)
        lines.append(f"SURF {surf_num}")
        lines.append(f"    SSID {surf_num}")
        comm = f"L{i+1} Front"
        if is_stop:
            comm += " - STOP"
        lines.append(f"    COMM {comm}")
        if is_stop:
            lines.append("    STOP")
        lines.append("    TYPE STANDARD")
        lines.append("    FIMP ")
        lines.append(f"    CURV {elem['c_front']:.16E} 0 0 0 0 \"\"")
        lines.append("    HIDE 0 0 0 0 0 0 0 0 0 0 0 0")
        lines.append("    MIRR 2 0")
        lines.append(f"    SLAB {surf_num}")
        lines.append(f"    DISZ {elem['d_glass']}")
        lines.append(f"    GLAS ___BLANK 1 0 {nd} 50 0 0 0 0 0 0 ")
        lines.append("    DIAM 0 0 0 0 1 \"\"")
        lines.append("    MEMA 0 0 0 0 1 \"\"")
        lines.append("    POPS 0 0 0 0 0 0 0 0 1 1 1 1 0 0 0 0")
        surf_num += 1

        # Back surface
        is_stop = (surf_num == stop_idx)
        if i < n - 1:
            disz = data['air_gaps'][i]
        else:
            disz = data['result']['bfl']
        lines.append(f"SURF {surf_num}")
        lines.append(f"    SSID {surf_num}")
        comm = f"L{i+1} Back"
        if is_stop:
            comm += " - STOP"
        lines.append(f"    COMM {comm}")
        if is_stop:
            lines.append("    STOP")
        lines.append("    TYPE STANDARD")
        lines.append("    FIMP ")
        lines.append(f"    CURV {elem['c_back']:.16E} 0 0 0 0 \"\"")
        lines.append("    HIDE 0 0 0 0 0 0 0 0 0 0 0 0")
        lines.append("    MIRR 2 0")
        lines.append(f"    SLAB {surf_num}")
        lines.append(f"    DISZ {disz}")
        lines.append("    DIAM 0 0 0 0 1 \"\"")
        lines.append("    MEMA 0 0 0 0 1 \"\"")
        lines.append("    POPS 0 0 0 0 0 0 0 0 1 1 1 1 0 0 0 0")
        surf_num += 1

    # Image surface
    lines.append(f"SURF {surf_num}")
    lines.append(f"    SSID {surf_num}")
    lines.append("    COMM IMA")
    lines.append("    TYPE STANDARD")
    lines.append("    FIMP ")
    lines.append("    CURV 0.0 0 0 0 0 \"\"")
    lines.append("    HIDE 0 0 0 0 0 0 0 0 0 0 0 0")
    lines.append("    MIRR 2 0")
    lines.append(f"    SLAB {surf_num}")
    lines.append("    DISZ 0")
    lines.append("    DIAM 0 0 0 0 1 \"\"")
    lines.append("    MEMA 0 0 0 0 1 \"\"")
    lines.append("    POPS 0 0 0 0 0 0 0 0 1 1 1 1 0 0 0 0")

    lines.append("BLNK ")
    lines.append("TOL TOFF   0   0 0.00000000000000E+00"
                 " 0.00000000000000E+00   0 0 0 0 0")
    lines.append("MNUM 1 1")
    lines.append("MOFF   0   1 \"\" 0 0 0 1 1 0 0.0 \"\" 0 0")

    # Write as UTF-16LE with BOM and CRLF line endings
    content = '\r\n'.join(lines) + '\r\n'
    with open(filepath, 'wb') as f:
        f.write(b'\xff\xfe')  # UTF-16LE BOM
        f.write(content.encode('utf-16-le'))


def main():
    # ====== SET YOUR JSON FILE NAME HERE ======
    json_file = "refined_30deg_6elem.json"
    # ==========================================

    json_path = os.path.join(os.path.dirname(__file__) or '.', json_file)

    with open(json_path) as f:
        data = json.load(f)

    zmx_path = json_path.replace('.json', '.zmx')
    write_zmx(zmx_path, data)
    print(f"Written: {zmx_path}")


if __name__ == "__main__":
    main()
